import { build } from 'esbuild';
import { mkdir, rm } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { syncSkillVersion } from './version.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
await syncSkillVersion(root);
const output = join(root, 'skills/mail-calendar/scripts');
await mkdir(output, { recursive: true });
await build({
  absWorkingDir: root,
  entryPoints: ['src/cli.mjs'],
  bundle: true,
  platform: 'node',
  target: 'node22.13',
  format: 'esm',
  minify: true,
  legalComments: 'none',
  outfile: join(output, 'mailcal.mjs'),
  banner: { js: `// Generated by npm run build.
import { createRequire as __mailcalCreateRequire } from 'node:module';
const require = __mailcalCreateRequire(import.meta.url);` },
});

// Retire the old fixed build outputs; scripts contains only the executable.
await rm(join(output, 'mailcal.mjs.LEGAL.txt'), { force: true });
await rm(join(output, 'THIRD_PARTY_NOTICES.txt'), { force: true });
await rm(join(output, '../THIRD_PARTY_NOTICES.md'), { force: true });
console.log(`Built ${relative(root, join(output, 'mailcal.mjs'))}.`);
